# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 132c28ba3bf71d217932244814c44e4c4ed0401fdd9a30c723ac6cc8634a4ab40b14ab7f31526005b807dca7a693046dbbf5cfbac904525833234139907db270

test:
  secret_key_base: a0922159511caaef2220c6a8d3284f5d88d18ac67e1bc31196c3241ed781769e3fdb161d66e2e78cfc59a0a22622cd5472f90b61494be39a1a365463b5d96999

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
